# Generated by Django 2.0.2 on 2018-04-06 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SignupApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TMSPayment',
            fields=[
                ('payment_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('amount', models.PositiveIntegerField()),
                ('mode', models.CharField(max_length=25)),
                ('tmsuser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SignupApp.TMSUser')),
            ],
        ),
    ]
